github: [MR.White Shadow, MR.Chaby]
patreon: MR.WHITE SHADOW
tidelift: whiteshadowofficial/Jessi-Setup
custom: ["https://github.com/whiteshadowofficial/Jessi-whatsapp-bot-md2", https://github.com/whiteshadowofficial/Jessi-Setup]
