github: [MR.White Shadow, MR.Chaby]
patreon: MR.WHITE SHADOW
tidelift: npm/octo-package
custom: ["https://github.com/whiteshadowofficial/Jessi-whatsapp-bot-md2", https://github.com/whiteshadowofficial/Jessi-Setup]
github: [octocat, surftocat]
patreon: Virus Fucker
tidelift: npm/octo-package
custom: ["https://github.com/whiteshadowofficial/Jessi-whatsapp-bot-md2", https://github.com/whiteshadowofficial/Jessi-Setup]
